<h1><center>Foundations of Deep Learning</center></h1>

---
Credits: Thanks and credits to materials from UCL and GeorgiaTech
---



In [ ]:
#@
Name = "Rishu Verma" #@param {type:"string"}

### Problem 1
--------------

Let $ \ T:\mathbb{R}^3 \rightarrow \mathbb{R}^4$ be defined by \
$$ Tx = \begin{bmatrix}
x_1 - 3x_3 \\
x_1+x_2 -6x_3 \\
x_2-3x_3 \\
x_1 - 3x_3
\end{bmatrix} $$

for every $x = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} \in \mathbb{R}^3$ Then, 


1) Write $\ T$ in matrix form.


*answer* :\
Given $x = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} \in \mathbb{R}^3$ and $ \ T:\mathbb{R}^3 \rightarrow \mathbb{R}^4$ be defined by \
$$ Tx = \begin{bmatrix}
x_1 - 3x_3 \\
x_1+x_2 -6x_3 \\
x_2-3x_3 \\
x_1 - 3x_3
\end{bmatrix} \rightarrow (1)$$ 

L.H.S of (1) i.e $Tx$ can also be represented as $T \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}$.\
Now, working on R.H.S of (1) to get it to the form of L.H.S. Also we know by the defination of linear transformation given function T is linear if $T : R^n → R^m$ satisifies additive and multiplication properties i.e,  

$1.   T(a+b) = T(a)+ T (b)$\
$2.   T(ax)= xT(a)$ 
\
∀ vectors a, b in $R^n$ and all scalars x .

Therfore, representing the R.H.S in terms of basis vector we get\
$x_1 \begin{bmatrix} 1 \\ 1 \\ 0 \\ 1 \end{bmatrix}$ +
$x_2 \begin{bmatrix} 0 \\ 1 \\ 1 \\ 0 \end{bmatrix}$ +
$x_3 \begin{bmatrix} -3 \\ -6 \\ -3 \\ -3 \end{bmatrix}$ 

This can also be written as $$ \begin{bmatrix}
1&0&-3\\
1&1&-6\\
0&1&-3\\
1&0&-3\\
\end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} → (2)$$ and we know $\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = x$. Hence from (2) we get matrix form of:
$$ T = \begin{bmatrix}
1&0&-3\\
1&1&-6\\
0&1&-3\\
1&0&-3\\
\end{bmatrix}$$

2) $T(3, -2, 4)$ 

*answer* : \
$T(3, -2, 4)$ that means $x_1 = 3, x_2 = -2, x_3 = 4$ putting in (1) we get
$$ \begin{bmatrix}
3 - 3*4 \\
3+(-2) -6*4 \\
-2-3*4 \\
3 - 3*4
\end{bmatrix} = \begin{bmatrix}
-9\\
-23 \\
-14 \\
-9
\end{bmatrix} $$
Hence, $T(3, -2, 4)$ = $(-9, -23, -14, -9)$

3) Is $\ T$ linear? Why ?

*answer* : \
Yes, T is linear because as per mentioned in the answer to question 1) the defination of linear transformation stats that a given function T is linear if $T : R^n → R^m$ satisifies additive and multiplication properties i.e,  

$1.   T(a+b) = T(a)+ T (b)$\
$2.   T(ax)= xT(a)$ 
\
∀ vectors a, b in $R^n$ and all scalars x .

and in our case $Tx$ satisifies these properties, which can be intutively justifed by looking at each component of the function T. Each term in the $T(x_1 - 3x_3,
x_1+x_2 -6x_3,
x_2-3x_3,
x_1 - 3x_3)$ is either a scaler times one of the component in $x$ and no two components are multiplied to each other. Also additive property is satisifed as there is just the scaled value of the components which is added and no other constant values.
Also as T(0) = 0 therefore the scalar property is satisified.
We can also give the proof of additive property of substituting values of column array (3x1) $[a_1 a_2 a_3]$ and column array b as (3x1) $[b_1 b_2 b_3]$.  


### Problem 2
--------------

Consider the following function of $x = (x1, x2, x3, x4, x5, x6)$:

$$
f(x) = \sigma \Big(\log \Big(5  \Big(max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6) \Big) \Big) + \frac{1}{2} \Big)
$$

where $\sigma$ is the sigmoid function

$$
  \sigma(x) = \frac{1}{1+e^{-x}}
$$

Compute the gradient $\nabla_x f$ and evaluate it at $x = (-1, 3, 4, 5, -5, 7)$

*answer* :\
In this question we need to perform the partial derivative of function $f(x)$ with respect to $x_1, x_2, x_3, x_4, x_5, x_6$ but as we can see $f(x)$ from derivative point of view we seen as $y = v(u(x))$. If we consider $v$ as the $σ$ and $u(x)$ = $g(x)+ \frac{1}{2}$ where $g(x) = \log \Big(5  \Big(max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6) \Big)$.

Then by chain rule we know: if given $ y = v(u(x))$ then $\frac{dy}{dx} = \frac{dv}{du} . \frac{du}{dx}$

Simplifying by:
1. Finding the $\sigma'(x)$ \
    $\frac{d}{dx}σ(x) = \frac{d}{dx}\Big(\frac{1}{1+e^{-x}}\Big)$\
    By reciprocal rule: $\frac{d}{dx}\Big[\frac{1}{h(x)}\Big] = \frac{- h'(x)}{(h(x))^2}$\
    $ -\Big(\frac{\frac{d}{dx}(1) + \frac{d}{dx}(e^{-x})}{(1+e^{-x})^{2}}\Big) = \frac{e^{-x}}{(1+e^{-x})^{2}}$\
   (Used exponential rule for solving $\frac{d}{dx}(e^{-x}) = (-1).(e^{-x}) = -e^{-x}$) \
   \
    This upon further simplification can be written as:\
    $σ(x)(1-σ(x))$

2.  Applying addition rule on $u(x)$ which will result as:\
$\frac{du}{dx} = \frac{dg}{dx} + \frac{d}{dx}(\frac{1}{2})$ as we know the derivative of constant = 0 therefore, $\frac{du}{dx} = \frac{dg}{dx}$.\
\
Solving for $g(x)$ using the log rule of derivatives:\
$\frac{dg}{dx} = \frac{d}{dx} \Big(\log \Big(5  \Big(max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6) \Big) = \frac{1}{5(h(x))}. 5. h'(x)  = \frac{1}{(h(x))}. h'(x)$\
where $h(x)$ = $max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6)$ 

3.  
We know by multiplication rule : $\frac{d}{dx} (f(x)g(x)) = f'(x)g(x) + g'(x)f(x)$\
Also we know if $f(x_1, x_2)$ = $max\{x_1, x_2\}$ then value of this fuction will evaluate as $x_1$ if $x_1 ≥ x_2$ and $x_2$ otherwise.\
Therefore\
 $\frac{\partial f}{\partial x_1} = 1$ if $x_1 > x_2$ and 0 otherwise\
 $\frac{\partial f}{\partial x_2} = 1$ if $x_2 > x_1$ and 0 otherwise

Performaing derivatives on h(x) with respect to $x_1, x_2, x_3, x_4, x_5, x_6$ By multiplicative rule and derivation of max function:\
 Considering the given values of $x_1$ = -1 and $x_2$ = 3 and $x_2$>$x_1$ $\frac{\partial h}{\partial x_1}$ =  0\
 Considering the given values of $x_1$ = -1 and $x_2$ = 3 and $x_2$>$x_1$ $\frac{\partial h}{\partial x_2}$ =  $\frac{x_3}{x_4} = \frac{4}{5} = 0.8$\
 $\frac{\partial h}{\partial x_3}$ =  $\frac{max\{x_1, x_2\}}{x_4} = \frac{3}{5} = 0.6$\
 Considering $\frac{d}{dx}\Big(\frac{1}{x}\Big) = -x^{-2}$ → $\frac{\partial h}{\partial x_4}$ =  $\frac{max\{x_1, x_2\}.x_3}{-x_4^{2}} = -\frac{3*4}{25} = -0.48$ \
$\frac{\partial h}{\partial x_5}$ =  -1\
$\frac{\partial h}{\partial x_6}$ =  -1 \

Considering we are evaluating for given values of $x = (-1, 3, 4, 5, -5, 7)$. I have directly put values in the derivation for simplicity.

4. Now applying the chain rule on 1, 2, 3 above we get:\
$\frac{d y}{d x}$ = $\sigma'(u(x)).\frac{1}{(h(x))}. h'(x)$:\
$\frac{\partial y }{\partial x_1} = \sigma(u(x)).(1-\sigma(u(x)).\frac{1}{(h(x))}. 0 = 0$  \
$\frac{\partial y }{\partial x_2} = \sigma(u(x)).(1-\sigma(u(x)).\frac{1}{(h(x))}. 0.8 = 0.35709771799814977 $ \
$\frac{\partial y }{\partial x_3} = \sigma(u(x)).(1-\sigma(u(x)).\frac{1}{(h(x))}. 0.6 = 0.2678232884986123 $\
$\frac{\partial y }{\partial x_4} = \sigma(u(x)).(1-\sigma(u(x)).\frac{1}{(h(x))}. -0.48 = -0.21425863079888982 $\
$\frac{\partial y }{\partial x_5} = \sigma(u(x)).(1-\sigma(u(x)).\frac{1}{(h(x))}. -1 = -0.44637214749768717 $\
$\frac{\partial y }{\partial x_6} = \sigma(u(x)).(1-\sigma(u(x)).\frac{1}{(h(x))}. -1 = -0.44637214749768717 $ 

where value of $\sigma(u(x)).(1-\sigma(u(x)) = 0.17855$ and $\frac{1}{(h(x))}$ = 2.49.

Hence: gradient $\nabla_x f$ evaluate it at $x = (-1, 3, 4, 5, -5, 7)$  will be [0, 0.3571, 0.2678, -0.2143, -0.44637, -0.44637].



### Problem 3
-------------

$a = [2, 6, 1, 9, 10, 3, 27, 5, 7, 14, 24, 3]$

Get all items in range $(5, 10]$ from $a$

Note: Use only indexing methods, do not use iteration or if conditions

In [2]:
import numpy as np
## write your code under this line:
a = np.array([2,6,1,9,10,3,27,5,7,14,24,3])
b = np.take(a,np.where((a>5) & (a<=10)))
print(b)

##can also be done without "Take"
c = a[np.where((a>5) & (a<=10))]
print(c)
#----------------------------------

[[ 6  9 10  7]]
[ 6  9 10  7]


### Problem 4
--------------

Let 

$$x = [3, 4, 5]$$


$$W = \begin{bmatrix} 1 & 5 & 3 \\ 2 & 5 & 5 \\5 & 5 &1 \end{bmatrix}$$

Compute


In [2]:
x = np.array([3, 4, 5])

In [3]:
W = np.array([[1, 5, 3], [2, 5, 5], [5,5,1]])

1) $x^T$

In [63]:
## write your code under this line:
y = x.transpose()
print(y)
#----------------------------------

[3 4 5]


2) $z = Wx^T$

In [66]:
## write your code under this line:
z = np.matmul(W, y)
print(z)
#----------------------------------

[38 51 40]


3) Write a function softmax:
$$
  softmax(x)_i = \frac{e^{x_i}}{\sum_j e^{x_j}}
$$


In [55]:
def softmax(x):
  # x is a numpy array of length 3
  ## write your code under this line:
  expo = np.exp(x)
  res = expo/np.sum(expo)
  #----------------------------------
  return res  # return correct result

compute $softmax(z)$ :

In [56]:
## write your code under this line:
softmax(z)
#----------------------------------

array([2.26028655e-06, 9.99981038e-01, 1.67013841e-05])

----------------------------